export const Strings = {
  login: 'Login',
  signUp: 'Sign Up',
  reviewRestaurants: 'Review Restaurants',
  email: 'Email',
  password: 'Password',
  firstName: 'First Name',
  lastName: 'Last Name',
  dontHaveAccount: 'Don\'t have account? ',
  alreadyHaveAccount: 'Already have Account? ',
  role: 'Role',
  gender: 'Gender',
  phoneNum: 'Phone Number',
  enterFirstName: 'Enter first name',
  enterLastName: 'Enter last name',
  enterEmil: 'Enter email',
  enterPassword: 'Enter password',
  enterPhoneNum: 'Enter phone number',
  selectGender: 'Select Gender',
  selectRole: 'Select Role',
  editProfile: 'Edit Profile',
  deleteRestaurantMessage: 'Are you sure you want to delete this restaurant?',
  deleteReviewMessage: 'Are you sure you want to delete this review?',
  deleteRestaurantTitle: 'Delete Restaurant',
  deleteReviewTitle: 'Delete Review',
  camera: 'Camera',
  gallery: 'Gallery',
  uploadPicture: 'Upload Picture',
  uploadPhoto: 'Upload Photo',
  settings: 'Settings',
  cancel: 'Cancel',
  storagePermissionTitle: 'ReviewRestaurants Needs to Access Photos and Videos',
  storagePermissionMessage:
    'ReviewRestaurants Needs Storage permission to access Photos and Videos. Please go to settings and turn on Storage permissions.',
  photosPermission: 'ReviewRestaurants needs Permission to access photos',
  photosPermissionMessage:
    'ReviewRestaurants needs your permission to use your Photo library to access photos',
  cameraPermissionTitle: 'ReviewRestaurants Needs to Access Camera',
  cameraPermissionMessage:
    'ReviewRestaurants Needs Storage permission to access Camera. Please go to settings and turn on Camera permissions.',
  name: 'Name',
  enterRestaurantName: 'Enter restaurant name',
  location: 'Location',
  enterLocation: 'Enter Location',
  description: 'Description',
  enterDescription: 'Enter Description',
  establishedAt: 'Established At ',
  addRestaurant: 'Add Restaurant',
  selectDate: 'Select Date',
  comment: 'Comment',
  enterYourComment: 'Enter your comment',
  submitReview: 'Submit Review',
  readMore: 'Read More',
  allComments: 'All Comments',
  leaveAComment: 'Leave A Comment',
  reply: 'Reply',
  enterReply: 'Enter Reply',
  leaveAReply: 'Leave A Reply',
  badCredential: 'Bad Credentials',
  logout: 'Logout',
  visitDate: 'Visit Date',
  previousReviews: 'Previous Reviews',
  totalReviews: 'Total Reviews : ',
  avgRating: 'Avg. Rating : ',
  replied: 'Replied Successfully',
  createReviewSuccess: 'Review Created Successful',
  createReviewFail: 'Review Created Failure',
  createRestaurantSuccess: 'Restaurant Created Successful',
  createRestaurantFail: 'Restaurant Created Failure',
  accountCreatedSuccessful: 'Account Created Successful',
  accountCreatedFailure: 'Account Created Failure',
  loginSuccessful: 'Login Successful',
  loginFailure: 'Incorrect email/password',
  createRestaurant: 'Create Restaurant',
  edit: 'Edit',
  restaurantUpdateSuccess: 'Restaurant Updated Successfully',
  restaurantUpdateFailure: 'Restaurant Update Failure',
  updateRestaurant: 'Update Restaurant',
  updateReview: 'Update Review',
  updateReviewSuccess: 'Review Updated Successfully',
  updateReviewFailure: 'Review Updated Failure',
  save: 'Save',
  profile: 'Profile',
  restaurantDetails: 'Restaurant Details',
  profileUpdated: 'Profile Updated Successfully',
  userDeleted: 'User Deleted Successfully',
  restaurantsDeleted: 'Restaurants Deleted Successfully',
  confirmPassword: 'Confirm Password',
  noRecordFound: 'No List Items are Found belong to this category',
  highestRatedReview: 'Highest Rated Review',
  userReview: 'User Review',
  lowestRatedReview: 'Lowest Rated Review',
  lastReview: 'Latest Review',
  otherReviews: 'Other Reviews',
  noRestaurantFound: 'No Restaurants Found',
  noReviewFound: 'No Reviews Found',
  applyFilters: 'Apply Filters',
}
