export const Strings = {
  login: 'Login',
  signUp: 'Sign Up',
  reviewRestaurants: 'Review Restaurants',
  email: 'Email',
  password: 'Password',
  firstName: 'First Name',
  lastName: 'Last Name',
  dontHaveAccount: "Don't have account? ",
  alreadyHaveAccount: 'Already have Account? ',
  role: 'Role',
  gender: 'Gender',
  phoneNum: 'Phone Number',
  enterFirstName: 'Enter first name',
  enterLastName: 'Enter last name',
  enterEmil: 'Enter email',
  enterPassword: 'Enter password',
  enterPhoneNum: 'Enter phone number',
  selectGender: 'Select Gender',
  selectRole: 'Select Role',
  camera: 'Camera',
  gallery: 'Gallery',
  uploadPicture: 'Upload Picture',
  uploadPhoto: 'Upload Photo',
  settings: 'Settings',
  cancel: 'Cancel',
  storagePermissionTitle: 'ReviewRestaurants Needs to Access Photos and Videos',
  storagePermissionMessage:
    'ReviewRestaurants Needs Storage permission to access Photos and Videos. Please go to settings and turn on Storage permissions.',
  photosPermission: 'ReviewRestaurants needs Permission to access photos',
  photosPermissionMessage:
    'ReviewRestaurants needs your permission to use your Photo library to access photos',
  cameraPermissionTitle: 'ReviewRestaurants Needs to Access Camera',
  cameraPermissionMessage:
    'ReviewRestaurants Needs Storage permission to access Camera. Please go to settings and turn on Camera permissions.',
  name: 'Name',
  enterRestaurantName: 'Enter restaurant name',
  location: 'Location',
  enterLocation: 'Enter Location',
  description: 'Description',
  enterDescription: 'Enter Description',
  establishedAt: 'Established At ',
  addRestaurant: 'Add Restaurant',
  selectDate: 'Select Date',
  comment: 'Comment',
  enterYourComment: 'Enter your comment',
  submitReview: 'Submit Review',
  readMore: 'Read More',
  allComments: 'All Comments',
  leaveAComment: 'Leave A Comment',
  reply: 'Reply',
  enterReply: 'Enter Reply',
  leaveAReply: 'Leave A Reply',
  badCredential: 'Bad Credentials'
}
